import { createFileRoute } from "@tanstack/react-router";
import { useCallback, useEffect, useState } from "react";
import { toast } from "sonner";
import { RefreshCw, Sparkles, MousePointerClick, ShoppingCart, BadgeIndianRupee, Save } from "lucide-react";
import { useAuth, useCatalog } from "@/lib/store";
import { formatINR } from "@/lib/data";
import {
  recommendationAnalyticsFn,
  getRecommendationSettingsFn,
  saveRecommendationSettingsFn,
  rebuildRecommendationsFn,
} from "@/lib/recommendations.functions";

export const Route = createFileRoute("/admin/recommendations")({
  component: AdminRecommendationsPage,
  head: () => ({
    meta: [
      { title: "Recommendation analytics — Kartogo admin" },
      { name: "description", content: "Impressions, clicks, add-to-cart and revenue generated by Kartogo product recommendations, plus scoring controls." },
    ],
  }),
});

type Analytics = Awaited<ReturnType<typeof recommendationAnalyticsFn>>;
type Settings = Awaited<ReturnType<typeof getRecommendationSettingsFn>>;

const SETTING_LABELS: Record<string, string> = {
  view_weight: "Product view weight",
  search_weight: "Search weight",
  favorite_weight: "Wishlist weight",
  cart_weight: "Add-to-cart weight",
  purchase_weight: "Purchase weight",
  repeat_purchase_bonus: "Repeat purchase bonus",
  min_co_purchase_count: "Min co-purchase count",
  recommendation_limit: "Products per section",
  min_recommendation_score: "Minimum score",
};

function Stat({ icon: Icon, label, value, sub }: { icon: typeof Sparkles; label: string; value: string; sub?: string }) {
  return (
    <div className="rounded-2xl border border-border bg-card p-4">
      <div className="flex items-center gap-2 text-muted-foreground">
        <Icon className="h-4 w-4" />
        <span className="text-xs font-bold uppercase tracking-wide">{label}</span>
      </div>
      <div className="mt-2 font-display text-2xl font-extrabold">{value}</div>
      {sub ? <div className="text-xs text-muted-foreground">{sub}</div> : null}
    </div>
  );
}

function AdminRecommendationsPage() {
  const { adminToken } = useAuth();
  const { products } = useCatalog();
  const [data, setData] = useState<Analytics | null>(null);
  const [settings, setSettings] = useState<Settings | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);

  const name = useCallback(
    (id: string) => products.find((p) => p.id === id)?.name ?? id,
    [products],
  );

  const load = useCallback(async () => {
    if (!adminToken) return;
    setLoading(true);
    try {
      const [a, s] = await Promise.all([
        recommendationAnalyticsFn({ data: { adminToken, days: 30 } }),
        getRecommendationSettingsFn({ data: { adminToken } }),
      ]);
      setData(a);
      setSettings(s);
    } catch (err) {
      toast.error((err as Error).message);
    } finally {
      setLoading(false);
    }
  }, [adminToken]);

  useEffect(() => { void load(); }, [load]);

  const save = async () => {
    if (!adminToken || !settings) return;
    setBusy(true);
    try {
      await saveRecommendationSettingsFn({
        data: { adminToken, settings: settings as unknown as Record<string, number> },
      });
      toast.success("Recommendation settings saved");
    } catch (err) {
      toast.error((err as Error).message);
    } finally { setBusy(false); }
  };

  const rebuild = async () => {
    if (!adminToken) return;
    setBusy(true);
    try {
      const res = await rebuildRecommendationsFn({ data: { adminToken } });
      toast.success(`Rebuilt ${res.pairs} product pairs for ${res.customers} customers`);
      await load();
    } catch (err) {
      toast.error((err as Error).message);
    } finally { setBusy(false); }
  };

  const pct = (n: number) => `${(n * 100).toFixed(1)}%`;

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <div>
          <h1 className="font-display text-2xl font-extrabold">Recommendation analytics</h1>
          <p className="text-sm text-muted-foreground">Last 30 days of real shopper behaviour.</p>
        </div>
        <div className="flex items-center gap-2">
          <button onClick={() => void load()} disabled={loading} className="inline-flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-sm font-bold">
            <RefreshCw className={`h-4 w-4 ${loading ? "animate-spin" : ""}`} /> Refresh
          </button>
          <button onClick={() => void rebuild()} disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-primary px-3 py-2 text-sm font-bold text-primary-foreground">
            <Sparkles className="h-4 w-4" /> Rebuild engine
          </button>
        </div>
      </div>

      {data && (
        <>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <Stat icon={Sparkles} label="Impressions" value={String(data.impressions)} />
            <Stat icon={MousePointerClick} label="Clicks" value={String(data.clicks)} sub={`CTR ${pct(data.clickRate)}`} />
            <Stat icon={ShoppingCart} label="Added to cart" value={String(data.addToCart)} sub={`Rate ${pct(data.cartRate)}`} />
            <Stat icon={BadgeIndianRupee} label="Revenue" value={formatINR(data.recRevenue)} sub={`${data.recOrders} orders · avg ${formatINR(data.avgRecOrderValue)}`} />
          </div>

          <div className="grid gap-4 lg:grid-cols-3">
            <div className="rounded-2xl border border-border bg-card p-4">
              <h2 className="font-display text-lg font-extrabold">Top recommended</h2>
              <ul className="mt-2 space-y-1 text-sm">
                {data.topRecommended.length === 0 && <li className="text-muted-foreground">No impressions yet.</li>}
                {data.topRecommended.map((r) => (
                  <li key={r.productId} className="flex justify-between gap-3">
                    <span className="truncate">{name(r.productId)}</span>
                    <span className="font-bold">{r.count}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="rounded-2xl border border-border bg-card p-4">
              <h2 className="font-display text-lg font-extrabold">Top pairs</h2>
              <ul className="mt-2 space-y-1 text-sm">
                {data.topPairs.length === 0 && <li className="text-muted-foreground">Not enough order history yet.</li>}
                {data.topPairs.map((p) => (
                  <li key={`${p.productId}-${p.associatedProductId}`} className="flex justify-between gap-3">
                    <span className="truncate">{name(p.productId)} + {name(p.associatedProductId)}</span>
                    <span className="font-bold">{p.count}</span>
                  </li>
                ))}
              </ul>
            </div>
            <div className="rounded-2xl border border-border bg-card p-4">
              <h2 className="font-display text-lg font-extrabold">Due for replenishment</h2>
              <ul className="mt-2 space-y-1 text-sm">
                {data.topReplenishment.length === 0 && <li className="text-muted-foreground">No predictions due.</li>}
                {data.topReplenishment.map((r) => (
                  <li key={r.productId} className="flex justify-between gap-3">
                    <span className="truncate">{name(r.productId)}</span>
                    <span className="font-bold">{r.count} customers</span>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </>
      )}

      {settings && (
        <div className="rounded-2xl border border-border bg-card p-4">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div>
              <h2 className="font-display text-lg font-extrabold">Scoring controls</h2>
              <p className="text-sm text-muted-foreground">Tune how strongly each behaviour influences suggestions.</p>
            </div>
            <button onClick={() => void save()} disabled={busy} className="inline-flex items-center gap-2 rounded-xl bg-primary px-3 py-2 text-sm font-bold text-primary-foreground">
              <Save className="h-4 w-4" /> Save
            </button>
          </div>
          <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {Object.entries(SETTING_LABELS).map(([key, label]) => (
              <label key={key} className="text-sm">
                <span className="font-semibold">{label}</span>
                <input
                  type="number"
                  step="0.5"
                  value={Number((settings as unknown as Record<string, number>)[key] ?? 0)}
                  onChange={(e) =>
                    setSettings({ ...settings, [key]: Number(e.target.value) } as Settings)
                  }
                  className="mt-1 w-full rounded-xl border border-border bg-background px-3 py-2"
                />
              </label>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}
