/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SupplierRouteImport } from './routes/supplier'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RequestServiceRouteImport } from './routes/request-service'
import { Route as RefundsRouteImport } from './routes/refunds'
import { Route as RefundReturnsRouteImport } from './routes/refund-returns'
import { Route as PrintRouteImport } from './routes/print'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SupplierIndexRouteImport } from './routes/supplier.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SupplierOrdersRouteImport } from './routes/supplier.orders'
import { Route as SupplierAccountRouteImport } from './routes/supplier.account'
import { Route as RateOrderOrderIdRouteImport } from './routes/rate-order.$orderId'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as AdminUnserviceableRouteImport } from './routes/admin.unserviceable'
import { Route as AdminSurgeRouteImport } from './routes/admin.surge'
import { Route as AdminSalesRouteImport } from './routes/admin.sales'
import { Route as AdminRefundRequestsRouteImport } from './routes/admin.refund-requests'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as AdminDeliveryRouteImport } from './routes/admin.delivery'
import { Route as AdminCancellationsRouteImport } from './routes/admin.cancellations'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierRoute = SupplierRouteImport.update({
  id: '/supplier',
  path: '/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestServiceRoute = RequestServiceRouteImport.update({
  id: '/request-service',
  path: '/request-service',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundsRoute = RefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundReturnsRoute = RefundReturnsRouteImport.update({
  id: '/refund-returns',
  path: '/refund-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintRoute = PrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierIndexRoute = SupplierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupplierRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SupplierOrdersRoute = SupplierOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => SupplierRoute,
} as any)
const SupplierAccountRoute = SupplierAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SupplierRoute,
} as any)
const RateOrderOrderIdRoute = RateOrderOrderIdRouteImport.update({
  id: '/rate-order/$orderId',
  path: '/rate-order/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUnserviceableRoute = AdminUnserviceableRouteImport.update({
  id: '/unserviceable',
  path: '/unserviceable',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSurgeRoute = AdminSurgeRouteImport.update({
  id: '/surge',
  path: '/surge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesRoute = AdminSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundRequestsRoute = AdminRefundRequestsRouteImport.update({
  id: '/refund-requests',
  path: '/refund-requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCancellationsRoute = AdminCancellationsRouteImport.update({
  id: '/cancellations',
  path: '/cancellations',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/print': typeof PrintRoute
  '/refund-returns': typeof RefundReturnsRoute
  '/refunds': typeof RefundsRoute
  '/request-service': typeof RequestServiceRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supplier': typeof SupplierRouteWithChildren
  '/support': typeof SupportRoute
  '/topup': typeof TopupRoute
  '/wallet': typeof WalletRoute
  '/wishlist': typeof WishlistRoute
  '/admin/cancellations': typeof AdminCancellationsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/refund-requests': typeof AdminRefundRequestsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/surge': typeof AdminSurgeRoute
  '/admin/unserviceable': typeof AdminUnserviceableRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/rate-order/$orderId': typeof RateOrderOrderIdRoute
  '/supplier/account': typeof SupplierAccountRoute
  '/supplier/orders': typeof SupplierOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/supplier/': typeof SupplierIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/print': typeof PrintRoute
  '/refund-returns': typeof RefundReturnsRoute
  '/refunds': typeof RefundsRoute
  '/request-service': typeof RequestServiceRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/topup': typeof TopupRoute
  '/wallet': typeof WalletRoute
  '/wishlist': typeof WishlistRoute
  '/admin/cancellations': typeof AdminCancellationsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/refund-requests': typeof AdminRefundRequestsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/surge': typeof AdminSurgeRoute
  '/admin/unserviceable': typeof AdminUnserviceableRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/rate-order/$orderId': typeof RateOrderOrderIdRoute
  '/supplier/account': typeof SupplierAccountRoute
  '/supplier/orders': typeof SupplierOrdersRoute
  '/admin': typeof AdminIndexRoute
  '/supplier': typeof SupplierIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/delivery': typeof DeliveryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/orders': typeof OrdersRoute
  '/print': typeof PrintRoute
  '/refund-returns': typeof RefundReturnsRoute
  '/refunds': typeof RefundsRoute
  '/request-service': typeof RequestServiceRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/supplier': typeof SupplierRouteWithChildren
  '/support': typeof SupportRoute
  '/topup': typeof TopupRoute
  '/wallet': typeof WalletRoute
  '/wishlist': typeof WishlistRoute
  '/admin/cancellations': typeof AdminCancellationsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/refund-requests': typeof AdminRefundRequestsRoute
  '/admin/sales': typeof AdminSalesRoute
  '/admin/surge': typeof AdminSurgeRoute
  '/admin/unserviceable': typeof AdminUnserviceableRoute
  '/category/$slug': typeof CategorySlugRoute
  '/product/$id': typeof ProductIdRoute
  '/rate-order/$orderId': typeof RateOrderOrderIdRoute
  '/supplier/account': typeof SupplierAccountRoute
  '/supplier/orders': typeof SupplierOrdersRoute
  '/admin/': typeof AdminIndexRoute
  '/supplier/': typeof SupplierIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/delivery'
    | '/login'
    | '/menu'
    | '/orders'
    | '/print'
    | '/refund-returns'
    | '/refunds'
    | '/request-service'
    | '/search'
    | '/sitemap.xml'
    | '/supplier'
    | '/support'
    | '/topup'
    | '/wallet'
    | '/wishlist'
    | '/admin/cancellations'
    | '/admin/delivery'
    | '/admin/feedback'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/products'
    | '/admin/refund-requests'
    | '/admin/sales'
    | '/admin/surge'
    | '/admin/unserviceable'
    | '/category/$slug'
    | '/product/$id'
    | '/rate-order/$orderId'
    | '/supplier/account'
    | '/supplier/orders'
    | '/admin/'
    | '/supplier/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/delivery'
    | '/login'
    | '/menu'
    | '/orders'
    | '/print'
    | '/refund-returns'
    | '/refunds'
    | '/request-service'
    | '/search'
    | '/sitemap.xml'
    | '/support'
    | '/topup'
    | '/wallet'
    | '/wishlist'
    | '/admin/cancellations'
    | '/admin/delivery'
    | '/admin/feedback'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/products'
    | '/admin/refund-requests'
    | '/admin/sales'
    | '/admin/surge'
    | '/admin/unserviceable'
    | '/category/$slug'
    | '/product/$id'
    | '/rate-order/$orderId'
    | '/supplier/account'
    | '/supplier/orders'
    | '/admin'
    | '/supplier'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/delivery'
    | '/login'
    | '/menu'
    | '/orders'
    | '/print'
    | '/refund-returns'
    | '/refunds'
    | '/request-service'
    | '/search'
    | '/sitemap.xml'
    | '/supplier'
    | '/support'
    | '/topup'
    | '/wallet'
    | '/wishlist'
    | '/admin/cancellations'
    | '/admin/delivery'
    | '/admin/feedback'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/partners'
    | '/admin/products'
    | '/admin/refund-requests'
    | '/admin/sales'
    | '/admin/surge'
    | '/admin/unserviceable'
    | '/category/$slug'
    | '/product/$id'
    | '/rate-order/$orderId'
    | '/supplier/account'
    | '/supplier/orders'
    | '/admin/'
    | '/supplier/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  DeliveryRoute: typeof DeliveryRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  OrdersRoute: typeof OrdersRoute
  PrintRoute: typeof PrintRoute
  RefundReturnsRoute: typeof RefundReturnsRoute
  RefundsRoute: typeof RefundsRoute
  RequestServiceRoute: typeof RequestServiceRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupplierRoute: typeof SupplierRouteWithChildren
  SupportRoute: typeof SupportRoute
  TopupRoute: typeof TopupRoute
  WalletRoute: typeof WalletRoute
  WishlistRoute: typeof WishlistRoute
  CategorySlugRoute: typeof CategorySlugRoute
  ProductIdRoute: typeof ProductIdRoute
  RateOrderOrderIdRoute: typeof RateOrderOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier': {
      id: '/supplier'
      path: '/supplier'
      fullPath: '/supplier'
      preLoaderRoute: typeof SupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-service': {
      id: '/request-service'
      path: '/request-service'
      fullPath: '/request-service'
      preLoaderRoute: typeof RequestServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refunds': {
      id: '/refunds'
      path: '/refunds'
      fullPath: '/refunds'
      preLoaderRoute: typeof RefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-returns': {
      id: '/refund-returns'
      path: '/refund-returns'
      fullPath: '/refund-returns'
      preLoaderRoute: typeof RefundReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/': {
      id: '/supplier/'
      path: '/'
      fullPath: '/supplier/'
      preLoaderRoute: typeof SupplierIndexRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/supplier/orders': {
      id: '/supplier/orders'
      path: '/orders'
      fullPath: '/supplier/orders'
      preLoaderRoute: typeof SupplierOrdersRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/supplier/account': {
      id: '/supplier/account'
      path: '/account'
      fullPath: '/supplier/account'
      preLoaderRoute: typeof SupplierAccountRouteImport
      parentRoute: typeof SupplierRoute
    }
    '/rate-order/$orderId': {
      id: '/rate-order/$orderId'
      path: '/rate-order/$orderId'
      fullPath: '/rate-order/$orderId'
      preLoaderRoute: typeof RateOrderOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/unserviceable': {
      id: '/admin/unserviceable'
      path: '/unserviceable'
      fullPath: '/admin/unserviceable'
      preLoaderRoute: typeof AdminUnserviceableRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/surge': {
      id: '/admin/surge'
      path: '/surge'
      fullPath: '/admin/surge'
      preLoaderRoute: typeof AdminSurgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales': {
      id: '/admin/sales'
      path: '/sales'
      fullPath: '/admin/sales'
      preLoaderRoute: typeof AdminSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refund-requests': {
      id: '/admin/refund-requests'
      path: '/refund-requests'
      fullPath: '/admin/refund-requests'
      preLoaderRoute: typeof AdminRefundRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cancellations': {
      id: '/admin/cancellations'
      path: '/cancellations'
      fullPath: '/admin/cancellations'
      preLoaderRoute: typeof AdminCancellationsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCancellationsRoute: typeof AdminCancellationsRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminRefundRequestsRoute: typeof AdminRefundRequestsRoute
  AdminSalesRoute: typeof AdminSalesRoute
  AdminSurgeRoute: typeof AdminSurgeRoute
  AdminUnserviceableRoute: typeof AdminUnserviceableRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCancellationsRoute: AdminCancellationsRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminRefundRequestsRoute: AdminRefundRequestsRoute,
  AdminSalesRoute: AdminSalesRoute,
  AdminSurgeRoute: AdminSurgeRoute,
  AdminUnserviceableRoute: AdminUnserviceableRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SupplierRouteChildren {
  SupplierAccountRoute: typeof SupplierAccountRoute
  SupplierOrdersRoute: typeof SupplierOrdersRoute
  SupplierIndexRoute: typeof SupplierIndexRoute
}

const SupplierRouteChildren: SupplierRouteChildren = {
  SupplierAccountRoute: SupplierAccountRoute,
  SupplierOrdersRoute: SupplierOrdersRoute,
  SupplierIndexRoute: SupplierIndexRoute,
}

const SupplierRouteWithChildren = SupplierRoute._addFileChildren(
  SupplierRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  DeliveryRoute: DeliveryRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  OrdersRoute: OrdersRoute,
  PrintRoute: PrintRoute,
  RefundReturnsRoute: RefundReturnsRoute,
  RefundsRoute: RefundsRoute,
  RequestServiceRoute: RequestServiceRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupplierRoute: SupplierRouteWithChildren,
  SupportRoute: SupportRoute,
  TopupRoute: TopupRoute,
  WalletRoute: WalletRoute,
  WishlistRoute: WishlistRoute,
  CategorySlugRoute: CategorySlugRoute,
  ProductIdRoute: ProductIdRoute,
  RateOrderOrderIdRoute: RateOrderOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
